"""Team orchestration module for orbit.

Provides multi-worker team coordination with tmux-based process management,
phased execution pipelines, role-based task routing, and dynamic scaling.
"""

from .contracts import (
    TEAM_NAME_SAFE_PATTERN,
    WORKER_NAME_SAFE_PATTERN,
    TASK_ID_SAFE_PATTERN,
    TEAM_TASK_STATUSES,
    TEAM_TERMINAL_TASK_STATUSES,
    TEAM_TASK_STATUS_TRANSITIONS,
    TEAM_EVENT_TYPES,
    TEAM_WAKEABLE_EVENT_TYPES,
    TEAM_TASK_APPROVAL_STATUSES,
    is_terminal_task_status,
    can_transition_task_status,
    is_wakeable_event_type,
)
from .orchestrator import (
    TeamPhase,
    TerminalPhase,
    AnyPhase,
    TeamState,
    PhaseTransition,
    create_team_state,
    can_resume_team_state,
    transition_phase,
    is_valid_transition,
    is_terminal_phase,
    get_phase_agents,
    get_phase_instructions,
)
from .role_router import (
    RoleRouterResult,
    load_role_prompt,
    is_known_role,
    list_available_roles,
    route_task_to_role,
)
from .runtime import (
    TeamRuntime,
    TeamSnapshot,
    TeamWorkerSnapshot,
    TeamTaskSummary,
    StartTeamOptions,
    start_team,
)
from .scaling import (
    ScaleUpResult,
    ScaleDownResult,
    ScaleDownOptions,
    ScaleError,
    is_scaling_enabled,
    scale_up,
    scale_down,
)
from .worktree import (
    WorktreeMode,
    WorktreeModeDisabled,
    WorktreeModeDetached,
    WorktreeModeNamed,
    PlannedWorktreeTarget,
    EnsureWorktreeResult,
    is_git_repository,
    plan_worktree_target,
    ensure_worktree,
    rollback_provisioned_worktrees,
    parse_worktree_mode,
    assert_clean_leader_workspace,
)
from .tmux_session import (
    TeamSession,
    TeamWorkerCli,
    TeamWorkerLaunchMode,
    WorkerProcessLaunchSpec,
    is_tmux_available,
    sanitize_team_name,
    create_team_session,
    send_to_worker,
    is_worker_alive,
    wait_for_worker_ready,
    teardown_worker_panes,
    destroy_team_session,
    list_team_sessions,
)
from .worker_bootstrap import (
    generate_worker_overlay,
    generate_initial_inbox,
    generate_task_assignment_inbox,
    generate_shutdown_inbox,
    generate_trigger_message,
    generate_mailbox_trigger_message,
    generate_leader_mailbox_trigger,
    apply_worker_overlay,
    strip_worker_overlay,
    write_team_worker_instructions_file,
    write_worker_role_instructions_file,
    remove_team_worker_instructions_file,
)

__all__ = [
    # Contracts
    "TEAM_NAME_SAFE_PATTERN",
    "WORKER_NAME_SAFE_PATTERN",
    "TASK_ID_SAFE_PATTERN",
    "TEAM_TASK_STATUSES",
    "TEAM_TERMINAL_TASK_STATUSES",
    "TEAM_TASK_STATUS_TRANSITIONS",
    "TEAM_EVENT_TYPES",
    "TEAM_WAKEABLE_EVENT_TYPES",
    "TEAM_TASK_APPROVAL_STATUSES",
    "is_terminal_task_status",
    "can_transition_task_status",
    "is_wakeable_event_type",
    # Orchestrator
    "TeamPhase",
    "TerminalPhase",
    "AnyPhase",
    "TeamState",
    "PhaseTransition",
    "create_team_state",
    "can_resume_team_state",
    "transition_phase",
    "is_valid_transition",
    "is_terminal_phase",
    "get_phase_agents",
    "get_phase_instructions",
    # Role router
    "RoleRouterResult",
    "load_role_prompt",
    "is_known_role",
    "list_available_roles",
    "route_task_to_role",
    # Runtime
    "TeamRuntime",
    "TeamSnapshot",
    "TeamWorkerSnapshot",
    "TeamTaskSummary",
    "StartTeamOptions",
    "start_team",
    # Scaling
    "ScaleUpResult",
    "ScaleDownResult",
    "ScaleDownOptions",
    "ScaleError",
    "is_scaling_enabled",
    "scale_up",
    "scale_down",
    # Worktree
    "WorktreeMode",
    "WorktreeModeDisabled",
    "WorktreeModeDetached",
    "WorktreeModeNamed",
    "PlannedWorktreeTarget",
    "EnsureWorktreeResult",
    "is_git_repository",
    "plan_worktree_target",
    "ensure_worktree",
    "rollback_provisioned_worktrees",
    "parse_worktree_mode",
    "assert_clean_leader_workspace",
    # Tmux
    "TeamSession",
    "TeamWorkerCli",
    "TeamWorkerLaunchMode",
    "WorkerProcessLaunchSpec",
    "is_tmux_available",
    "sanitize_team_name",
    "create_team_session",
    "send_to_worker",
    "is_worker_alive",
    "wait_for_worker_ready",
    "teardown_worker_panes",
    "destroy_team_session",
    "list_team_sessions",
    # Worker bootstrap
    "generate_worker_overlay",
    "generate_initial_inbox",
    "generate_task_assignment_inbox",
    "generate_shutdown_inbox",
    "generate_trigger_message",
    "generate_mailbox_trigger_message",
    "generate_leader_mailbox_trigger",
    "apply_worker_overlay",
    "strip_worker_overlay",
    "write_team_worker_instructions_file",
    "write_worker_role_instructions_file",
    "remove_team_worker_instructions_file",
]
