"""Application constants for orbit."""

from constants.defaults import (
    DEFAULT_MODEL,
    DEFAULT_MAX_TOKENS,
    DEFAULT_TEMPERATURE,
    DEFAULT_TIMEOUT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_CACHE_TTL,
    DEFAULT_HISTORY_LIMIT,
    DEFAULT_CONFIG_DIR,
    DEFAULT_DATA_DIR,
    DEFAULT_LOG_LEVEL,
    DEFAULT_SERVER_HOST,
    DEFAULT_SERVER_PORT,
    RATE_LIMIT_REQUESTS,
    RATE_LIMIT_WINDOW,
    MAX_CONTEXT_TOKENS,
    MAX_FILE_SIZE_BYTES,
    MAX_PLUGIN_COUNT,
)
from constants.env_vars import (
    ENV_API_KEY,
    ENV_MODEL,
    ENV_CONFIG_DIR,
    ENV_DATA_DIR,
    ENV_LOG_LEVEL,
    ENV_DEBUG,
    ENV_SERVER_HOST,
    ENV_SERVER_PORT,
    ENV_CACHE_ENABLED,
    ENV_PLUGIN_DIR,
    ENV_MAX_TOKENS,
    ENV_TEMPERATURE,
)
from constants.colors import (
    RESET,
    BOLD,
    DIM,
    Colors,
    Theme,
    DEFAULT_THEME,
    DARK_THEME,
    LIGHT_THEME,
)

__all__ = [
    "DEFAULT_MODEL",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "Colors",
    "Theme",
    "ENV_API_KEY",
    "ENV_MODEL",
]
